### ISSUE TITLE
Scrolling blocked/broken

### ISSUE THREAD

**Issue by Nojuuu** [finnish-easylist-addition/finnish-easylist-addition#406]
~`https://olutposti.fi/`~ Fixed in uAssets.

On mobile:
`https://www.gigantti.fi/tietokoneet-ja-toimistotarvikkeet/tietokoneet`

**Comment by Nojuuu** [comment]
The issue on gigantti seems to be caused by this in their css:
```css
.mat-drawer-container, .mat-drawer-content {
   overflow-x: unset !important;
   overflow-y: unset !important;
}
```
and the issue is still there even if cookies are accepted.

Should we even do anything about that since it seems to be their own issue? @peace2000
